In [3]:
import pandas as pd
import sqlite3 as sq
import matplotlib as mpl
from matplotlib import rcParams
import matplotlib.pyplot as plt
import numpy as np
import geopandas as gpd
import fiona
import os
import py7zr
import io

In [4]:
archive_path = r"G:\GNRC_GIS_STRUCTURE\UrbanSim\2050\Urbansim_final_run_with_TDM_feedback\2050RTP-Hary-confirmed (block)_recap_with_job_classes.7z"

with py7zr.SevenZipFile(archive_path, mode="r") as archive:
    archive.extract(path=r"C:\temp", targets=["2050RTP-Hary-confirmed (block) - 2023.csv"])

df = pd.read_csv(r"C:\temp\2050RTP-Hary-confirmed (block) - 2023.csv")

In [6]:
df.head(2)

,year,geo_level,geo_level_id,geo_level_name,density_households_acre,density_jobs_acre,density_units_acre,employment_capacity,household_population,household_population_density_acres,...,sector_3,sector_4,sector_5,sector_6,sector_7,sector_8,severe_rent_burden,sum_total_households,sum_total_jobs,sum_total_units
0,2023,block,470831203003000,NaN,0.05,0.0,0.05,3.145802,18.161201,0.10479,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0,9.0
1,2023,block,470831203003090,NaN,0.00,0.0,0.00,4.576094,0.000000,0.00000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [18]:
col_dict = {'sector_0': 'Other', 'sector_1': 'Service', 'sector_2': 'Retail', 'sector_3': 'Office', 'geo_level_id': 'GEO_ID',
               'sector_4': 'Medical', 'sector_5': 'Industrial', 'sector_6': 'Government', 'sector_7': 
               'Food service', 'sector_8': 'Education', 'household_population': 'hhpop', 'sum_total_households': 'hh', 'sum_total_jobs': 'emp'}

In [19]:
df = df.rename(columns = col_dict)

In [20]:
df_filtered = df[['GEO_ID', 'hhpop', 'hh', 'emp', 'Other', 'Service', 'Retail', 'Office', 'Medical', 'Industrial', 'Government', 'Food service', 'Education']]

In [21]:
df_filtered.head()

,GEO_ID,hhpop,hh,emp,Other,Service,Retail,Office,Medical,Industrial,Government,Food service,Education
0,470831203003000,18.161201,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,470831203003090,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,471190103013047,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,471690902001031,86.982590,32.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,471190112003048,4.779263,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0